### ISSUE TITLE
Event blacklisted despite conf saying not to

### ISSUE THREAD

**Issue by retdredfakir** [actionml/universal-recommender#15]
Hi,

We use pio 0.10.0, the UR v 0.5.0 for our project.

We have a problem. Despite our configuration the engine generates a query to Elasticsearch that blacklists primary event items.
Here an example of the query we send to Pio:
curl -H "Content-Type: application/json" -d '{ "user": "4e810ef4-977a-4f04-b585-cf2c2996ec93", "num": 11 }' http://localhost:8001/queries.json

In return Pio generates the query for ES that you'll find in the attached file 'es_query.txt".

Our engine.json is also attached. The parameter blacklistEvent is set to [].

Pat Ferrel advised us to open an issue here, as I guess he suspects there might be a problem.

Thanks in advance for your help.
[ES_Query.txt](https://github.com/actionml/universal-recommender/files/903211/ES_Query.txt)
[engine.json.txt](https://github.com/actionml/universal-recommender/files/903213/engine.json.txt)

**Comment by pferrel** [comment]
Yes, a bug, fixed just now. The develop branch should now contain the fix, `blacklistEvents` was not working properly at all.

Now no blacklistEvent param defaults to the conversion/primary event, an empty list `"blacklistEvents": []` will filter no items by events, only the query blacklist of items will apply, and a normal list of event names works as documented.

Also the integration test passes. 

Please feel free to try out the `develop` branch, it is now RC1 of UR v0.6.0
