### ISSUE TITLE
When training, logged number of events is garbage

### ISSUE THREAD

**Issue by jsyrjala** [actionml/universal-recommender#18]
When running command pio train, something like this is logged to console:

```
[INFO] [DataSource] Received events List(asset-watch, category-watch) 
[INFO] [DataSource] Number of events List(11, 14)
```

Here the second line doesn't have anything to do with actual number of events. Instead it prints how long the event names are: e.g asset-watch is 11 chars long and category-watch is 14 chars long.

The code in question is here:
https://github.com/actionml/universal-recommender/blob/master/src/main/scala/DataSource.scala#L88

```
logger.info(s"Received events ${eventRDDs.map(_._1)}")
logger.info(s"Number of events ${eventRDDs.map(_._1.length)}")
```

The second line should be something else. Maybe `${eventRDDs.map(_._2.length)}`

**Comment by pferrel** [comment]
Yikes, calculating the size of an RDD is a heavyweight task, this is now removed.

Thanks!
