### ISSUE TITLE
Invalid Integration Test Pop Model

### ISSUE THREAD

**Issue by steven-haddix** [actionml/universal-recommender#19]
Looks like the integration test for "trend 2 day" is missing the corresponding engine.json.

```
Checking for needed files
File not found: trend-2-day-engine.json
```

Is this now trend-engine-4-days-ago.json? or is this an invalid test?

**Comment by pferrel** [comment]
Thanks.

Those tests are not maintained. We left some old tests in for example purposes. Will have a look but don't expect a "fix", we'd remove it if it's confusing.

**Comment by steven-haddix** [comment]
That makes perfect sense. Just noticed and wasn't sure if it was on purpose. Thanks!
