### ISSUE TITLE
Pio build error

### ISSUE THREAD

**Issue by creever** [actionml/universal-recommender#21]
Hi!

Could you help me in this issue please? If you need more info please let me know.

I fetched the latest release (0.6.0) and when I try to run a pio build I get the following error:

> Using existing engine manifest JSON at /var/pio/engines/ur/manifest.json
> [INFO] [Console$] Using command '/PredictionIO-0.10.0-incubating/sbt/sbt' at the current working directory to build.
> [INFO] [Console$] If the path above is incorrect, this process will fail.
> [INFO] [Console$] Uber JAR disabled, but current working directory does not look like an engine project directory. Please delete lib/pio-assembly-0.10.0-incubating.jar manually.
> [INFO] [Console$] Going to run: /PredictionIO-0.10.0-incubating/sbt/sbt  package assemblyPackageDependency
> [ERROR] [Console$] [error] impossible to get artifacts when data has not been loaded. IvyNode = org.xerial.snappy#snappy-java;1.0.5
> [ERROR] [Console$] [error] (*:update) java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.xerial.snappy#snappy-java;1.0.5
> [ERROR] [Console$] [error] Total time: 6 s, completed May 24, 2017 10:11:19 PM
> [ERROR] [Console$] Return code of previous step is 1. Aborting.

If I checkout the 0.5.0 version everything is fine. I'm using PredictionIO 10.

**Comment by pferrel** [comment]
0.6.0 is meant for PIO 0.11.0

Off hand I can’t think of a reason it wouldn’t work with 0.10.0. Try deleting your old jars in target/scala-2.10 and the manifest.json and build again.

The better fix is update pio and the ur to clean directories and proceed. You shouldn’t loose any data.
 

On May 24, 2017, at 3:20 PM, creever <notifications@github.com> wrote:

Hi!

Could you help me in this issue please? If you need more info please let me know.

I fetched the latest release (0.6.0) and when I try to run a pio build I get the following error:

Using existing engine manifest JSON at /var/pio/engines/ur/manifest.json
[INFO] [Console$] Using command '/PredictionIO-0.10.0-incubating/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled, but current working directory does not look like an engine project directory. Please delete lib/pio-assembly-0.10.0-incubating.jar manually.
[INFO] [Console$] Going to run: /PredictionIO-0.10.0-incubating/sbt/sbt package assemblyPackageDependency
[ERROR] [Console$] [error] impossible to get artifacts when data has not been loaded. IvyNode = org.xerial.snappy#snappy-java;1.0.5
[ERROR] [Console$] [error] (*:update) java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.xerial.snappy#snappy-java;1.0.5
[ERROR] [Console$] [error] Total time: 6 s, completed May 24, 2017 10:11:19 PM
[ERROR] [Console$] Return code of previous step is 1. Aborting.

If I checkout the 0.5.0 version everything is fine. I'm using PredictionIO 10.

**Comment by clappdev** [comment]
Thanks for the help! I changed to 0.11.0 but now I'm facing an other issue :\ I upgrade the version numbers  for the elastic, hadoop, spark, scala and I get the following errors:

::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[INFO] [Engine$] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] 	:: org.apache.mahout#mahout-math-scala_2.11;0.13.0: not found
[INFO] [Engine$] [warn] 	:: org.apache.mahout#mahout-spark_2.11;0.13.0: not found
[INFO] [Engine$] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::

As I read Mahout 0.13.0 does not support scala 2.11 yet. Should I install predictionio with scala 2.10? 

These are my installed versions:
ENV PIO_VERSION 0.11.0
ENV SPARK_VERSION 2.1.1
ENV ELASTICSEARCH_VERSION 5.4.0
ENV HBASE_VERSION 1.2.5
ENV SCALA_VERSION 2.11.8
ENV HADOOP_VERSION 2.7

Should I change anything else?

**Comment by creever** [comment]
Thanks for the help! I changed to 0.11.0 but now I'm facing an other issue :\ I upgrade the version numbers for the elastic, hadoop, spark, scala and I get the following errors:

::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] :: UNRESOLVED DEPENDENCIES ::
[INFO] [Engine$] [warn] ::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] :: org.apache.mahout#mahout-math-scala_2.11;0.13.0: not found
[INFO] [Engine$] [warn] :: org.apache.mahout#mahout-spark_2.11;0.13.0: not found
[INFO] [Engine$] [warn] ::::::::::::::::::::::::::::::::::::::::::::::

As I read Mahout 0.13.0 does not support scala 2.11 yet. Should I install predictionio with scala 2.10?

These are my installed versions:
ENV PIO_VERSION 0.11.0
ENV SPARK_VERSION 2.1.1
ENV ELASTICSEARCH_VERSION 5.4.0
ENV HBASE_VERSION 1.2.5
ENV SCALA_VERSION 2.11.8
ENV HADOOP_VERSION 2.7

Should I change anything else?

**Comment by pferrel** [comment]
the UR is not compatible with ES5, use ES 1.7.6 for now. We have a PR but it's not ready yet. There are significant changes in the 5 API that have to be reconciled including using only the REST API instead of the older Transport client.

Also Mahout requires you to build from source to get a Scala 2.11 version, they only released a 2.10 version accessible from Maven.

**Comment by pferrel** [comment]
Just talked to the Mahout guys and they want to have a scala 2.11 binary in a week or 2. Same for UR with ES5 

FYI

**Comment by pferrel** [comment]
Please use the google group for these questions so others get the benefit
