### ISSUE TITLE
 When will support ES 5.x

### ISSUE THREAD

**Issue by FelixHo** [actionml/universal-recommender#24]
Hi~, I intend to use UR in my new project, as far as I know the latest version of UR still does not support ES 5.x, from the forum(Google groups) i know that the work (support ES 5.x) is ongoing, I would like to know the following questions:

0x00:
 _**Does it mean that the current UR is only compatible with ES 1.x + PIO?**_

0x01:
  _**Is the ES 1.7 satisfying fast queries based on a model of small and medium-sized data of two billion events?**_

0x02:
 _**Will the next version plan to support ES 5.x ? (because I was in the selection stage, I would like to know how long this work will be completed.)**_

**Thanks !**

**Comment by pferrel** [comment]
1) yes
2) yes, 25ms latency, scale out to indefinite number of simultaneous queries and this includes one query to HBase and one to Elasticsearch. 5.x is generally a little faster but it's only one component.
3) The UR PR for ES5 is made but still needs work, may 90% done. planned for 0.6.1 but no timeline on it, depends on how much need for it arises.

If you use the list for these inquiries others benefit from the answers.
