### ISSUE TITLE
No engine found

### ISSUE THREAD

**Issue by pedropinto** [actionml/universal-recommender#38]
Hello. I'm trying to deploy a model using ur but I got into some problems. First, I got several dependency errors when I was trying to execute `examples/integration-tests`. After I solved those, I couldn't deploy a model because the system can't find any engine.

I was wondering if everyone can clone the project and run `examples/integration-tests` straight-away with no problems.

Here is the console log:
`Building and delpoying model
[INFO] [Engine$] Using command '/usr/local/PredictionIO-0.12.0-incubating/sbt/sbt' at /home/***/Documents/***/PredictionIO/ur to build.
[INFO] [Engine$] If the path above is incorrect, this process will fail.
[INFO] [Engine$] Uber JAR disabled. Making sure lib/pio-assembly-0.12.0-incubating.jar is absent.
[INFO] [Engine$] Going to run: /usr/local/PredictionIO-0.12.0-incubating/sbt/sbt  package assemblyPackageDependency in /home/***/Documents/***/PredictionIO/ur
[INFO] [Engine$] Compilation finished successfully.
[INFO] [Engine$] Looking for an engine...
[ERROR] [Engine$] No engine found. Your build might have failed. Aborting.`

Thank you :)

**Comment by pferrel** [comment]
please post questions to the group https://groups.google.com/forum/#!forum/actionml-user
so others can get the benefit of the answer.

You must train before you deploy. Not training is the usual reason for this.

**Comment by pferrel** [comment]
This fact was posted on the Google group mentioned above
